---

############################################
# Delete the Kubernetes cluster
############################################

- hosts: localhost
  connection: local
  tasks:
  - name: Delete the cluster
    shell: "kops delete cluster {{ cluster_name }} --state {{ state_store }} --yes"
