---

####################
# Create Kubernetes cluster using Kops
####################

- name: List clusters
  shell: "kops create clusters --state {{ state_store }}"
  register: get_clusters

- name: Configure the cluster
  shell: "kops create cluster --associate-public-ip=false --bastion=true --channel=alpha --cloud=aws --dns-zone={{ dns_zone }} --master-size={{ master_size }} --master-zones={{ aws_zones }} --network-cidr={{ network_cidr }} --networking={{ kubernetes_networking }} --node-count={{ node_count }} --node-size={{ node_size }} --target=direct --topology=private --zones={{ aws_zones }} --ssh-public-key={{ ssh_public_key }} --name={{ cluster_name }} --state {{ state_store }}"

- name: Create the physical cluster
  shell: "kops update cluster {{ cluster_name }} --yes --state {{ state_store }}"

- name: Verify that all Kubernetes nodes are ready
  shell: kubectl get nodes | grep "Ready" | wc -l
  register: cmd_result
  until: cmd_result.stdout.find('{{ node_count + 3 }}') != -1
  retries: 20
  delay: 60
